# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1isM8pTaxtvKxAO8STANMz0cMAMW-fXjb
"""

import rebound
import numpy as np
import matplotlib.pyplot as plt
from concurrent.futures import ThreadPoolExecutor

# ============================================================
# Parâmetros em unidades normalizadas (distância Sol-Júpiter = 1)
# ============================================================
mu = 0.001
m_sol = 1.0 - mu
m_jup = mu

R_SOL = 0.005          # raio do Sol (normalizado)
R_JUP = 0.0005         # raio de Júpiter
ESCAPE_R = 10.0

T_MAX = 10.0           # tempo pequeno para varrer o grid rapidamente
STEP = 0.05

# Grid de parâmetros
a_vals = np.linspace(0.5, 1.5, 51)        # 51 pontos em a
e_vals = np.linspace(1e-9, 0.5, 41)       # 41 pontos em e (evita e=0)
inc = 0.0

# ============================================================
# Função que integra uma partícula de teste
# ============================================================
def simular(a, e):
    sim = rebound.Simulation()
    sim.integrator = "bs"
    sim.dt = 0.01

    # Corpos primários (Júpiter em órbita circular)
    sim.add(m=m_sol, x=-mu, y=0, vx=0, vy=mu)
    sim.add(m=m_jup, x=1-mu, y=0, vx=0, vy=1-mu)
    # Partícula de teste
    sim.add(m=0.0, a=a, e=e, inc=inc, omega=0., f=0.)

    sim.particles[0].r = R_SOL
    sim.particles[1].r = R_JUP
    sim.particles[2].r = 0.0

    sim.collision = "direct"
    sim.exit_max_distance = ESCAPE_R
    sim.exit_min_distance = min(R_SOL, R_JUP)

    sim.move_to_com()

    t = 0.0
    try:
        while t < T_MAX:
            t_next = min(t + STEP, T_MAX)
            sim.integrate(t_next)
            t = t_next
    except rebound.Escape:
        return "escape"
    except (rebound.Collision, rebound.Encounter):
        # Verifica com quem ocorreu o encontro/colisão
        p = sim.particles[2]
        dx_sol = p.x - sim.particles[0].x
        dy_sol = p.y - sim.particles[0].y
        if np.hypot(dx_sol, dy_sol) < R_SOL:
            return "colisao_sol"
        else:
            return "colisao_jupiter"
    return "estavel"

# ============================================================
# Execução paralela
# ============================================================
def run_grid():
    tarefas = [(a, e) for a in a_vals for e in e_vals]
    resultados = {}
    with ThreadPoolExecutor(max_workers=8) as executor:
        futures = {executor.submit(simular, a, e): (a, e) for a, e in tarefas}
        for future in futures:
            a, e = futures[future]
            resultados[(a, e)] = future.result()
    return resultados

# ============================================================
# Plotagem dos resultados
# ============================================================
def plot_results(resultados):
    # Separa os pontos por tipo
    stable = []
    col_jup = []
    col_sol = []
    escape = []

    for (a, e), res in resultados.items():
        if res == "estavel":
            stable.append((a, e))
        elif res == "colisao_jupiter":
            col_jup.append((a, e))
        elif res == "colisao_sol":
            col_sol.append((a, e))
        elif res == "escape":
            escape.append((a, e))

    fig, ax = plt.subplots(figsize=(10, 6))

    # Plota cada categoria
    if stable:
        a_s, e_s = zip(*stable)
        ax.scatter(a_s, e_s, s=10, c='green', marker='o', label='Estável', alpha=0.7)
    if col_jup:
        a_cj, e_cj = zip(*col_jup)
        ax.scatter(a_cj, e_cj, s=10, c='red', marker='x', label='Colidiu Júpiter', alpha=0.7)
    if col_sol:
        a_cs, e_cs = zip(*col_sol)
        ax.scatter(a_cs, e_cs, s=10, c='orange', marker='^', label='Colidiu Sol', alpha=0.7)
    if escape:
        a_e, e_e = zip(*escape)
        ax.scatter(a_e, e_e, s=10, c='blue', marker='s', label='Escapou', alpha=0.7)

    # Linhas de colisão com Júpiter (órbita que tangencia a = 1)
    a_line = np.linspace(0.5, 1.0, 100)
    e_line1 = 1.0 / a_line - 1.0          # a(1+e)=1  -> e = 1/a - 1  (para a<1)
    ax.plot(a_line, e_line1, 'k--', linewidth=1.5, label='Colisão (afélio = 1)')

    a_line2 = np.linspace(1.0, 1.5, 100)
    e_line2 = 1.0 - 1.0 / a_line2         # a(1-e)=1  -> e = 1 - 1/a (para a>1)
    ax.plot(a_line2, e_line2, 'k--', linewidth=1.5, label='Colisão (periélio = 1)')

    # Ressonâncias de movimento médio (linhas verticais)
    resonances = {
        '1:2': (0.5)**(2/3),     # a = (1/2)^(2/3) ≈ 0.630
        '2:3': (2/3)**(2/3),     # ≈ 0.763
        '3:4': (3/4)**(2/3),     # ≈ 0.825
        '4:5': (4/5)**(2/3),     # ≈ 0.861
        '5:6': (5/6)**(2/3),     # ≈ 0.885
        '3:2': (3/2)**(2/3),     # ≈ 1.310
        '4:3': (4/3)**(2/3),     # ≈ 1.210
        '5:4': (5/4)**(2/3),     # ≈ 1.160
        '6:5': (6/5)**(2/3),     # ≈ 1.129
    }
    for name, a_res in resonances.items():
        if 0.5 <= a_res <= 1.5:
            ax.axvline(x=a_res, color='gray', linestyle=':', linewidth=1)
            ax.text(a_res, 0.47, name, rotation=90, fontsize=8, ha='center', va='bottom')

    # (Opcional) Ressonâncias seculares (para Júpiter com excentricidade real)
    # Valores aproximados: ν5 em a ≈ 0.73, ν6 em a ≈ 1.96 (fora do intervalo)
    # ax.axvline(x=0.73, color='purple', linestyle='-.', label='Secular ν5')
    # ax.text(0.73, 0.48, 'ν5', rotation=90, fontsize=8)

    ax.set_xlabel('Semi‑eixo maior a (AU)', fontsize=12)
    ax.set_ylabel('Excentricidade e', fontsize=12)
    ax.set_title(f'Grid (a,e) – Sobrevivência após t = {T_MAX:.0f} (μ = {mu})', fontsize=14)
    ax.set_xlim(0.5, 1.5)
    ax.set_ylim(0, 0.5)
    ax.grid(True, linestyle=':', alpha=0.5)
    ax.legend(loc='upper left', fontsize=9)
    plt.tight_layout()
    plt.show()

# ============================================================
# Main
# ============================================================
if __name__ == "__main__":
    print("Rodando grid (a=0.5..1.5, e=0..0.5)...")
    resultados = run_grid()
    print("Plotando resultados...")
    plot_results(resultados)

